version: '3.7'

services:
  licensing-service:
    # Собираем образ
    image: santygo77/license-service:0.0.1-SNAPSHOT

    # Прокидываем порты
    ports:
      - "8080:8080"

    # Определяем переменную окружения (профиль)
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_CONFIG_IMPORT=optional:configserver:http://localhost:8888"
