version: '3.7'

services:
  licensing-service:
    # Собираем образ
    image: santygo77/licensing-service:latest

    # Прокидываем порты
    ports:
      - "8080:8080"

    # Определяем переменную окружения
    environment:
      - "SPRIGN_PROFILES_ACTIVE=dev"

    networks:
      # Называет сеть, к которой принадлежит сервис
      backend:
        aliases:
          - "licenseservice" # Задает альтернативное имя хоста для службы в сети

# Создает настраиваемую сеть с именем backend и с типом bridge по умолчанию
networks:
  backend:
    driver: bridge
